/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuraProfile {
  'age' : bigint,
  'height' : number,
  'weightHistory' : Array<WeightEntry>,
  'biologicalSex' : string,
}
export interface Exercise {
  'id' : bigint,
  'creator' : Principal,
  'name' : string,
  'animationUrl' : [] | [string],
  'muscleGroup' : string,
  'youtubeUrl' : [] | [string],
}
export interface HabitEntry {
  'id' : bigint,
  'completionRate' : number,
  'habitType' : HabitType,
  'name' : string,
  'description' : [] | [string],
  'streakCount' : bigint,
}
export type HabitType = { 'quit' : null } |
  { 'build' : null };
export interface JournalEntry {
  'whatDidntGoWell' : string,
  'whatWentWell' : string,
  'whatToImprove' : string,
  'timestamp' : Time,
}
export interface ProgressPhoto {
  'id' : bigint,
  'notes' : [] | [string],
  'timestamp' : Time,
  'blobId' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightEntry { 'weight' : number, 'timestamp' : Time }
export interface WorkoutExercise {
  'id' : bigint,
  'exerciseId' : bigint,
  'name' : string,
  'sets' : Array<WorkoutSet>,
}
export interface WorkoutSession {
  'id' : bigint,
  'startTime' : Time,
  'endTime' : [] | [Time],
  'totalDuration' : [] | [bigint],
  'exercises' : Array<WorkoutExercise>,
  'restTime' : [] | [bigint],
  'activeTime' : [] | [bigint],
}
export interface WorkoutSet {
  'weight' : number,
  'reps' : bigint,
  'completed' : boolean,
  'notes' : [] | [string],
  'timestamp' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Journal Management
   */
  'addJournalEntry' : ActorMethod<[JournalEntry], undefined>,
  /**
   * / Media Management
   */
  'addProgressPhoto' : ActorMethod<[ProgressPhoto], bigint>,
  /**
   * / Weight Management
   */
  'addWeightEntry' : ActorMethod<[number], undefined>,
  /**
   * / Workout Management
   */
  'addWorkoutSession' : ActorMethod<[WorkoutSession], bigint>,
  /**
   * / Mixin component functionality
   */
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / BMR Calculation (simplified)
   */
  'calculateProfileStats' : ActorMethod<
    [],
    {
      'bmr' : number,
      'proteinTarget' : number,
      'fatTarget' : number,
      'carbTarget' : number,
      'dailyCalories' : number,
    }
  >,
  /**
   * / Exercise Management
   */
  'createExercise' : ActorMethod<[Exercise], bigint>,
  /**
   * / Habit Management
   */
  'createHabit' : ActorMethod<[HabitEntry], bigint>,
  'deleteExercise' : ActorMethod<[bigint], undefined>,
  'getCallerProfile' : ActorMethod<[], [] | [AuraProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [AuraProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExercises' : ActorMethod<[], Array<Exercise>>,
  'getHabits' : ActorMethod<[], Array<HabitEntry>>,
  'getJournals' : ActorMethod<[], Array<JournalEntry>>,
  'getPhotos' : ActorMethod<[], Array<ProgressPhoto>>,
  'getProfile' : ActorMethod<[Principal], AuraProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [AuraProfile]>,
  'getWorkouts' : ActorMethod<[], Array<WorkoutSession>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Read all profiles (admin permission required).
   */
  'readAllProfiles' : ActorMethod<
    [],
    { 'users' : Array<Principal>, 'profiles' : Array<AuraProfile> }
  >,
  'saveCallerUserProfile' : ActorMethod<[AuraProfile], undefined>,
  /**
   * / Core Functions
   * / Profile Management
   */
  'saveProfile' : ActorMethod<[AuraProfile], undefined>,
  /**
   * / HTTP Outcall Transform
   */
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateExercise' : ActorMethod<[bigint, Exercise], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];