/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const JournalEntry = IDL.Record({
  'whatDidntGoWell' : IDL.Text,
  'whatWentWell' : IDL.Text,
  'whatToImprove' : IDL.Text,
  'timestamp' : Time,
});
export const ProgressPhoto = IDL.Record({
  'id' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'blobId' : IDL.Text,
});
export const WorkoutSet = IDL.Record({
  'weight' : IDL.Float64,
  'reps' : IDL.Nat,
  'completed' : IDL.Bool,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
});
export const WorkoutExercise = IDL.Record({
  'id' : IDL.Nat,
  'exerciseId' : IDL.Nat,
  'name' : IDL.Text,
  'sets' : IDL.Vec(WorkoutSet),
});
export const WorkoutSession = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'endTime' : IDL.Opt(Time),
  'totalDuration' : IDL.Opt(IDL.Int),
  'exercises' : IDL.Vec(WorkoutExercise),
  'restTime' : IDL.Opt(IDL.Int),
  'activeTime' : IDL.Opt(IDL.Int),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Exercise = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'name' : IDL.Text,
  'animationUrl' : IDL.Opt(IDL.Text),
  'muscleGroup' : IDL.Text,
  'youtubeUrl' : IDL.Opt(IDL.Text),
});
export const HabitType = IDL.Variant({ 'quit' : IDL.Null, 'build' : IDL.Null });
export const HabitEntry = IDL.Record({
  'id' : IDL.Nat,
  'completionRate' : IDL.Float64,
  'habitType' : HabitType,
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'streakCount' : IDL.Nat,
});
export const WeightEntry = IDL.Record({
  'weight' : IDL.Float64,
  'timestamp' : Time,
});
export const AuraProfile = IDL.Record({
  'age' : IDL.Nat,
  'height' : IDL.Float64,
  'weightHistory' : IDL.Vec(WeightEntry),
  'biologicalSex' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJournalEntry' : IDL.Func([JournalEntry], [], []),
  'addProgressPhoto' : IDL.Func([ProgressPhoto], [IDL.Nat], []),
  'addWeightEntry' : IDL.Func([IDL.Float64], [], []),
  'addWorkoutSession' : IDL.Func([WorkoutSession], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateProfileStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'bmr' : IDL.Float64,
          'proteinTarget' : IDL.Float64,
          'fatTarget' : IDL.Float64,
          'carbTarget' : IDL.Float64,
          'dailyCalories' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'createExercise' : IDL.Func([Exercise], [IDL.Nat], []),
  'createHabit' : IDL.Func([HabitEntry], [IDL.Nat], []),
  'deleteExercise' : IDL.Func([IDL.Nat], [], []),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(AuraProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(AuraProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getHabits' : IDL.Func([], [IDL.Vec(HabitEntry)], ['query']),
  'getJournals' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getPhotos' : IDL.Func([], [IDL.Vec(ProgressPhoto)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [AuraProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AuraProfile)],
      ['query'],
    ),
  'getWorkouts' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'readAllProfiles' : IDL.Func(
      [],
      [
        IDL.Record({
          'users' : IDL.Vec(IDL.Principal),
          'profiles' : IDL.Vec(AuraProfile),
        }),
      ],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([AuraProfile], [], []),
  'saveProfile' : IDL.Func([AuraProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateExercise' : IDL.Func([IDL.Nat, Exercise], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const JournalEntry = IDL.Record({
    'whatDidntGoWell' : IDL.Text,
    'whatWentWell' : IDL.Text,
    'whatToImprove' : IDL.Text,
    'timestamp' : Time,
  });
  const ProgressPhoto = IDL.Record({
    'id' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'blobId' : IDL.Text,
  });
  const WorkoutSet = IDL.Record({
    'weight' : IDL.Float64,
    'reps' : IDL.Nat,
    'completed' : IDL.Bool,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
  });
  const WorkoutExercise = IDL.Record({
    'id' : IDL.Nat,
    'exerciseId' : IDL.Nat,
    'name' : IDL.Text,
    'sets' : IDL.Vec(WorkoutSet),
  });
  const WorkoutSession = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'endTime' : IDL.Opt(Time),
    'totalDuration' : IDL.Opt(IDL.Int),
    'exercises' : IDL.Vec(WorkoutExercise),
    'restTime' : IDL.Opt(IDL.Int),
    'activeTime' : IDL.Opt(IDL.Int),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'name' : IDL.Text,
    'animationUrl' : IDL.Opt(IDL.Text),
    'muscleGroup' : IDL.Text,
    'youtubeUrl' : IDL.Opt(IDL.Text),
  });
  const HabitType = IDL.Variant({ 'quit' : IDL.Null, 'build' : IDL.Null });
  const HabitEntry = IDL.Record({
    'id' : IDL.Nat,
    'completionRate' : IDL.Float64,
    'habitType' : HabitType,
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'streakCount' : IDL.Nat,
  });
  const WeightEntry = IDL.Record({
    'weight' : IDL.Float64,
    'timestamp' : Time,
  });
  const AuraProfile = IDL.Record({
    'age' : IDL.Nat,
    'height' : IDL.Float64,
    'weightHistory' : IDL.Vec(WeightEntry),
    'biologicalSex' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJournalEntry' : IDL.Func([JournalEntry], [], []),
    'addProgressPhoto' : IDL.Func([ProgressPhoto], [IDL.Nat], []),
    'addWeightEntry' : IDL.Func([IDL.Float64], [], []),
    'addWorkoutSession' : IDL.Func([WorkoutSession], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateProfileStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'bmr' : IDL.Float64,
            'proteinTarget' : IDL.Float64,
            'fatTarget' : IDL.Float64,
            'carbTarget' : IDL.Float64,
            'dailyCalories' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'createExercise' : IDL.Func([Exercise], [IDL.Nat], []),
    'createHabit' : IDL.Func([HabitEntry], [IDL.Nat], []),
    'deleteExercise' : IDL.Func([IDL.Nat], [], []),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(AuraProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(AuraProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getHabits' : IDL.Func([], [IDL.Vec(HabitEntry)], ['query']),
    'getJournals' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getPhotos' : IDL.Func([], [IDL.Vec(ProgressPhoto)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [AuraProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AuraProfile)],
        ['query'],
      ),
    'getWorkouts' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'readAllProfiles' : IDL.Func(
        [],
        [
          IDL.Record({
            'users' : IDL.Vec(IDL.Principal),
            'profiles' : IDL.Vec(AuraProfile),
          }),
        ],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([AuraProfile], [], []),
    'saveProfile' : IDL.Func([AuraProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateExercise' : IDL.Func([IDL.Nat, Exercise], [], []),
  });
};

export const init = ({ IDL }) => { return []; };