/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    id: bigint;
    creator: Principal;
    name: string;
    animationUrl?: string;
    muscleGroup: string;
    youtubeUrl?: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface WorkoutSession {
    id: bigint;
    startTime: Time;
    endTime?: Time;
    totalDuration?: bigint;
    exercises: Array<WorkoutExercise>;
    restTime?: bigint;
    activeTime?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface HabitEntry {
    id: bigint;
    completionRate: number;
    habitType: HabitType;
    name: string;
    description?: string;
    streakCount: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AuraProfile {
    age: bigint;
    height: number;
    weightHistory: Array<WeightEntry>;
    biologicalSex: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface WorkoutSet {
    weight: number;
    reps: bigint;
    completed: boolean;
    notes?: string;
    timestamp: Time;
}
export interface JournalEntry {
    whatDidntGoWell: string;
    whatWentWell: string;
    whatToImprove: string;
    timestamp: Time;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ProgressPhoto {
    id: bigint;
    notes?: string;
    timestamp: Time;
    blobId: string;
}
export interface WeightEntry {
    weight: number;
    timestamp: Time;
}
export interface WorkoutExercise {
    id: bigint;
    exerciseId: bigint;
    name: string;
    sets: Array<WorkoutSet>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum HabitType {
    quit = "quit",
    build = "build"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Journal Management
     */
    addJournalEntry(entry: JournalEntry): Promise<void>;
    /**
     * / Media Management
     */
    addProgressPhoto(photo: ProgressPhoto): Promise<bigint>;
    /**
     * / Weight Management
     */
    addWeightEntry(weight: number): Promise<void>;
    /**
     * / Workout Management
     */
    addWorkoutSession(session: WorkoutSession): Promise<bigint>;
    /**
     * / Mixin component functionality
     */
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / BMR Calculation (simplified)
     */
    calculateProfileStats(): Promise<{
        bmr: number;
        proteinTarget: number;
        fatTarget: number;
        carbTarget: number;
        dailyCalories: number;
    }>;
    /**
     * / Exercise Management
     */
    createExercise(exercise: Exercise): Promise<bigint>;
    /**
     * / Habit Management
     */
    createHabit(habit: HabitEntry): Promise<bigint>;
    deleteExercise(id: bigint): Promise<void>;
    getCallerProfile(): Promise<AuraProfile | null>;
    getCallerUserProfile(): Promise<AuraProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExercises(): Promise<Array<Exercise>>;
    getHabits(): Promise<Array<HabitEntry>>;
    getJournals(): Promise<Array<JournalEntry>>;
    getPhotos(): Promise<Array<ProgressPhoto>>;
    getProfile(user: Principal): Promise<AuraProfile>;
    getUserProfile(user: Principal): Promise<AuraProfile | null>;
    getWorkouts(): Promise<Array<WorkoutSession>>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Read all profiles (admin permission required).
     */
    readAllProfiles(): Promise<{
        users: Array<Principal>;
        profiles: Array<AuraProfile>;
    }>;
    saveCallerUserProfile(profile: AuraProfile): Promise<void>;
    /**
     * / Core Functions
     * / Profile Management
     */
    saveProfile(profile: AuraProfile): Promise<void>;
    /**
     * / HTTP Outcall Transform
     */
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateExercise(id: bigint, exercise: Exercise): Promise<void>;
}
import type { AuraProfile as _AuraProfile, Exercise as _Exercise, HabitEntry as _HabitEntry, HabitType as _HabitType, ProgressPhoto as _ProgressPhoto, Time as _Time, UserRole as _UserRole, WorkoutExercise as _WorkoutExercise, WorkoutSession as _WorkoutSession, WorkoutSet as _WorkoutSet, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addJournalEntry(arg0: JournalEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalEntry(arg0);
            return result;
        }
    }
    async addProgressPhoto(arg0: ProgressPhoto): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProgressPhoto(to_candid_ProgressPhoto_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProgressPhoto(to_candid_ProgressPhoto_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addWeightEntry(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeightEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeightEntry(arg0);
            return result;
        }
    }
    async addWorkoutSession(arg0: WorkoutSession): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkoutSession(to_candid_WorkoutSession_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkoutSession(to_candid_WorkoutSession_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateProfileStats(): Promise<{
        bmr: number;
        proteinTarget: number;
        fatTarget: number;
        carbTarget: number;
        dailyCalories: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateProfileStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateProfileStats();
            return result;
        }
    }
    async createExercise(arg0: Exercise): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createExercise(to_candid_Exercise_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExercise(to_candid_Exercise_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createHabit(arg0: HabitEntry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createHabit(to_candid_HabitEntry_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHabit(to_candid_HabitEntry_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteExercise(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExercise(arg0);
            return result;
        }
    }
    async getCallerProfile(): Promise<AuraProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<AuraProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercises();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercises();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabits(): Promise<Array<HabitEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabits();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabits();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJournals(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournals();
            return result;
        }
    }
    async getPhotos(): Promise<Array<ProgressPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotos();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotos();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<AuraProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<AuraProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkouts(): Promise<Array<WorkoutSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkouts();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkouts();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async readAllProfiles(): Promise<{
        users: Array<Principal>;
        profiles: Array<AuraProfile>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.readAllProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readAllProfiles();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: AuraProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveProfile(arg0: AuraProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateExercise(arg0: bigint, arg1: Exercise): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExercise(arg0, to_candid_Exercise_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExercise(arg0, to_candid_Exercise_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Exercise_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_HabitEntry_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HabitEntry): HabitEntry {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_HabitType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HabitType): HabitType {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_ProgressPhoto_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProgressPhoto): ProgressPhoto {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutExercise_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutExercise): WorkoutExercise {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutSession_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutSession): WorkoutSession {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutSet_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutSet): WorkoutSet {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AuraProfile]): AuraProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    creator: Principal;
    name: string;
    animationUrl: [] | [string];
    muscleGroup: string;
    youtubeUrl: [] | [string];
}): {
    id: bigint;
    creator: Principal;
    name: string;
    animationUrl?: string;
    muscleGroup: string;
    youtubeUrl?: string;
} {
    return {
        id: value.id,
        creator: value.creator,
        name: value.name,
        animationUrl: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.animationUrl)),
        muscleGroup: value.muscleGroup,
        youtubeUrl: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.youtubeUrl))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    completionRate: number;
    habitType: _HabitType;
    name: string;
    description: [] | [string];
    streakCount: bigint;
}): {
    id: bigint;
    completionRate: number;
    habitType: HabitType;
    name: string;
    description?: string;
    streakCount: bigint;
} {
    return {
        id: value.id,
        completionRate: value.completionRate,
        habitType: from_candid_HabitType_n36(_uploadFile, _downloadFile, value.habitType),
        name: value.name,
        description: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.description)),
        streakCount: value.streakCount
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    notes: [] | [string];
    timestamp: _Time;
    blobId: string;
}): {
    id: bigint;
    notes?: string;
    timestamp: Time;
    blobId: string;
} {
    return {
        id: value.id,
        notes: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp,
        blobId: value.blobId
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: _Time;
    endTime: [] | [_Time];
    totalDuration: [] | [bigint];
    exercises: Array<_WorkoutExercise>;
    restTime: [] | [bigint];
    activeTime: [] | [bigint];
}): {
    id: bigint;
    startTime: Time;
    endTime?: Time;
    totalDuration?: bigint;
    exercises: Array<WorkoutExercise>;
    restTime?: bigint;
    activeTime?: bigint;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.endTime)),
        totalDuration: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.totalDuration)),
        exercises: from_candid_vec_n46(_uploadFile, _downloadFile, value.exercises),
        restTime: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.restTime)),
        activeTime: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.activeTime))
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    exerciseId: bigint;
    name: string;
    sets: Array<_WorkoutSet>;
}): {
    id: bigint;
    exerciseId: bigint;
    name: string;
    sets: Array<WorkoutSet>;
} {
    return {
        id: value.id,
        exerciseId: value.exerciseId,
        name: value.name,
        sets: from_candid_vec_n49(_uploadFile, _downloadFile, value.sets)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: number;
    reps: bigint;
    completed: boolean;
    notes: [] | [string];
    timestamp: _Time;
}): {
    weight: number;
    reps: bigint;
    completed: boolean;
    notes?: string;
    timestamp: Time;
} {
    return {
        weight: value.weight,
        reps: value.reps,
        completed: value.completed,
        notes: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quit: null;
} | {
    build: null;
}): HabitType {
    return "quit" in value ? HabitType.quit : "build" in value ? HabitType.build : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HabitEntry>): Array<HabitEntry> {
    return value.map((x)=>from_candid_HabitEntry_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProgressPhoto>): Array<ProgressPhoto> {
    return value.map((x)=>from_candid_ProgressPhoto_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutSession>): Array<WorkoutSession> {
    return value.map((x)=>from_candid_WorkoutSession_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutExercise>): Array<WorkoutExercise> {
    return value.map((x)=>from_candid_WorkoutExercise_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutSet>): Array<WorkoutSet> {
    return value.map((x)=>from_candid_WorkoutSet_n50(_uploadFile, _downloadFile, x));
}
function to_candid_Exercise_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Exercise): _Exercise {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_HabitEntry_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HabitEntry): _HabitEntry {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_HabitType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HabitType): _HabitType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_ProgressPhoto_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProgressPhoto): _ProgressPhoto {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutExercise_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutExercise): _WorkoutExercise {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutSession_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutSession): _WorkoutSession {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutSet_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutSet): _WorkoutSet {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: Time;
    endTime?: Time;
    totalDuration?: bigint;
    exercises: Array<WorkoutExercise>;
    restTime?: bigint;
    activeTime?: bigint;
}): {
    id: bigint;
    startTime: _Time;
    endTime: [] | [_Time];
    totalDuration: [] | [bigint];
    exercises: Array<_WorkoutExercise>;
    restTime: [] | [bigint];
    activeTime: [] | [bigint];
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: value.endTime ? candid_some(value.endTime) : candid_none(),
        totalDuration: value.totalDuration ? candid_some(value.totalDuration) : candid_none(),
        exercises: to_candid_vec_n12(_uploadFile, _downloadFile, value.exercises),
        restTime: value.restTime ? candid_some(value.restTime) : candid_none(),
        activeTime: value.activeTime ? candid_some(value.activeTime) : candid_none()
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    exerciseId: bigint;
    name: string;
    sets: Array<WorkoutSet>;
}): {
    id: bigint;
    exerciseId: bigint;
    name: string;
    sets: Array<_WorkoutSet>;
} {
    return {
        id: value.id,
        exerciseId: value.exerciseId,
        name: value.name,
        sets: to_candid_vec_n15(_uploadFile, _downloadFile, value.sets)
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: number;
    reps: bigint;
    completed: boolean;
    notes?: string;
    timestamp: Time;
}): {
    weight: number;
    reps: bigint;
    completed: boolean;
    notes: [] | [string];
    timestamp: _Time;
} {
    return {
        weight: value.weight,
        reps: value.reps,
        completed: value.completed,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        timestamp: value.timestamp
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    creator: Principal;
    name: string;
    animationUrl?: string;
    muscleGroup: string;
    youtubeUrl?: string;
}): {
    id: bigint;
    creator: Principal;
    name: string;
    animationUrl: [] | [string];
    muscleGroup: string;
    youtubeUrl: [] | [string];
} {
    return {
        id: value.id,
        creator: value.creator,
        name: value.name,
        animationUrl: value.animationUrl ? candid_some(value.animationUrl) : candid_none(),
        muscleGroup: value.muscleGroup,
        youtubeUrl: value.youtubeUrl ? candid_some(value.youtubeUrl) : candid_none()
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    completionRate: number;
    habitType: HabitType;
    name: string;
    description?: string;
    streakCount: bigint;
}): {
    id: bigint;
    completionRate: number;
    habitType: _HabitType;
    name: string;
    description: [] | [string];
    streakCount: bigint;
} {
    return {
        id: value.id,
        completionRate: value.completionRate,
        habitType: to_candid_HabitType_n24(_uploadFile, _downloadFile, value.habitType),
        name: value.name,
        description: value.description ? candid_some(value.description) : candid_none(),
        streakCount: value.streakCount
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    notes?: string;
    timestamp: Time;
    blobId: string;
}): {
    id: bigint;
    notes: [] | [string];
    timestamp: _Time;
    blobId: string;
} {
    return {
        id: value.id,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        timestamp: value.timestamp,
        blobId: value.blobId
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HabitType): {
    quit: null;
} | {
    build: null;
} {
    return value == HabitType.quit ? {
        quit: null
    } : value == HabitType.build ? {
        build: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<WorkoutExercise>): Array<_WorkoutExercise> {
    return value.map((x)=>to_candid_WorkoutExercise_n13(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<WorkoutSet>): Array<_WorkoutSet> {
    return value.map((x)=>to_candid_WorkoutSet_n16(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
